'use strict';

module.exports = {
    /**
     * When editing your questions pay attention to your punctuation. Make sure you use question marks or periods.
     * Make sure the first answer is the correct one. Set at least ANSWER_COUNT answers, any extras will be shuffled in.
     */
    QUESTIONS_EN_GB: [
        {
            'The Eternal Champion is the endlessly reincarnating protagonist of which author?': [
              'Michael Moorcock',
              'Frank Herbert',
              'Roger Zelazny',
              'Edward E. Smith',
              'Robert E. Howard',
              'Howard Phillips Lovecraft',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Prince Corwin is the Shadow Traveling protagonist of which author?': [
              'Roger Zelazny',
              'Michael Moorcock',
              'Frank Herbert',
              'Edward E. Smith',
              'Robert E. Howard',
              'Howard Phillips Lovecraft',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The Miracle drug of Spice drives much of the politics in which authors works? ': [
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Edward E. Smith',
              'Robert E. Howard',
              'Howard Phillips Lovecraft',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The Galactic Patrol defended worlds against space pirates and worse in which authors works?': [
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Robert E. Howard',
              'Howard Phillips Lovecraft',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Conan the famed hyborian barbarian fought for survival and glory in which authors works?': [
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Howard Phillips Lovecraft',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The Crawling Chaos, soul of the Outer Gods, was born from the pages of which author?': [
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Henry Dorsett Case was a “Console Cowboy” in which authors works?': [
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Which author introduced the idea of the Three Laws of Robotics?': [
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The verb Grok, defined in the merriam-webster dictionary as “To understand profoundly and intuitively,” was invented by which author?': [
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The temporal policemen of The Time Patrol come from which author’s works?': [
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The science fiction Comedy of Manners omnibus, “Ten Points for Style,” was written by which author?': [
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The musician and witch Damiano is the protagonist in which author’s works?': [
              'Roberta Ann MacAvoy',
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Teela Brown was bred to be lucky in which author’s works?': [
              'Larry Niven',
              'Roberta Ann MacAvoy',
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Morgaine travel’s from world to world but ancient gates, destroying the very gates she uses in which author’s works?': [
              'C. J. Cherryh',
              'Larry Niven',
              'Roberta Ann MacAvoy',
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'You cannot lie in the language of Dragons, because it is the language of True Names, in which author’s works.': [
              'Ursula K. Le Guin',
              'C. J. Cherryh',
              'Larry Niven',
              'Roberta Ann MacAvoy',
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Philip K. Dick',
            ],
        },
        {
            'Substance D, a psychoactive drug with horrible side-effects, is poisoning America in which author’s works?': [
              'Philip K. Dick',
              'Ursula K. Le Guin',
              'C. J. Cherryh',
              'Larry Niven',
              'Roberta Ann MacAvoy',
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
            ],
        },
        {
            'Dorian Hawkmoon is..?': [
              'An Incarnation of the Eternal Champion',
              'A Prince of Amber',
              'A Dragon hiding among men.',
              'A Space Policeman',
              'A Time Policeman',
              'An undercover policeman',
              'An Allowed Burglar',
              'A cyberspace hacker',
            ],
        },
        {
            'Benedict is..?': [
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'A Dragon hiding among men.',
              'A Space Policeman',
              'A Time Policeman',
              'An undercover policeman',
              'An Allowed Burglar',
              'A cyberspace hacker',
            ],
        },
        {
            'Mayland Long is..?': [
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'A Space Policeman',
              'A Time Policeman',
              'An undercover policeman',
              'An Allowed Burglar',
              'A cyberspace hacker',
            ],
        },
        {
            'Drake Maijstral is..?': [
              'An Allowed Burglar',
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'A Space Policeman',
              'A Time Policeman',
              'An undercover policeman',
              'A cyberspace hacker',
            ],
        },
        {
            'Manse Everard is..?': [
              'A Time Policeman',
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'A Space Policeman',
              'An undercover policeman',
              'An Allowed Burglar',
              'A cyberspace hacker',
            ],
        },
        {
            'Kimball Kinnison is..?': [
              'A Space Policeman',
              'A Time Policeman',
              'An Allowed Burglar',
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'An undercover policeman',
              'A cyberspace hacker',
            ],
        },
        {
            'Bob Arctor is..?': [
              'An undercover policeman',
              'A Space Policeman',
              'A Time Policeman',
              'An Allowed Burglar',
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'A cyberspace hacker',
            ],
        },
        {
            'Henry Dorsett Case..?': [
              'A cyberspace hacker',
              'An undercover policeman',
              'A Space Policeman',
              'A Time Policeman',
              'An Allowed Burglar',
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
            ],
        },
        {
            'The following prayer is uttered in a work of Roger Zelazny. “Insofar as I may be heard by anything, which may or may not care what I say, I ask, if it matters, that you be forgiven for anything you may have done or failed to do which requires forgiveness. Conversely, if not forgiveness but something else may be required to insure any possible benefit for which you may be eligible after the destruction of your body, I ask that this, whatever it may be, be granted or withheld, as the case may be, in such a manner as to insure your receiving said benefit. I ask this in my capacity as your elected intermediary between yourself and that which may not be yourself, but which may have an interest in the matter of your receiving as much as it is possible for you to receive of this thing, and which may in some way be influenced by this ceremony. Amen.” Which work is it?': [
                'Creatures of Light and Darkness',
                'Lord of Light',
                'A Night in the Lonesome October',
                'The Doors of His Face, The Lamps of His Mouth, and Other Stories',
                'Lord Demon',
                'The Chronicles of Amber',
                'The Mask of Loki',
                'Jack of Shadows',
                'Dilvish, the Damned',
            ],
        },
        {
            'Which two authors shared characters?': [
                'Robert E. Howard and Howard Phillips Lovecraft',
                'Michael Moorcock and Frank Herbert',
                'Roger Zelazny and Isaac Asimov',
                'Edward E. Smith and Poul Anderson',
                'William Gibson and Robert A. Heinlein',
                'Walter Jon Williams and Roberta Ann MacAvoy',
                'Ursula K. Le Guin and Philip K. Dick',
            ],
        },
        {
            'Which title is not a compilation of previously published works?': [
                'The Word of Unbinding',
                'Stormbringer',
                'Dilvish, the Damned',
                'Ten Points for Style',
                'The Chronicles of Amber',
            ],
        },
        {
            'What is the meaning of life?': [
                'Forty two',
                'To find happiness',
                'You have to find it for yourself',
                'To pass on your genes',
                'To find meaning',
            ],
        },
        {
            'Who is Corwin’s son?': [
                'Merlin',
                'Brand',
                'Oberon',
                'Random',
                'Eric',
            ],
        },
        {
            'Who here has not flirted with being a villain??': [
                'None of these',
                'Jack of Shadows from Jack of Shadows',
                'DuQuesne from Skylark',
                'Corwin from Chronicles of Amber',
                'Elric of Melniboné of Elric of Melniboné',
            ],
        },
    ],
    QUESTIONS_EN_US: [
        {
            'The Eternal Champion is the endlessly reincarnating protagonist of which author?': [
              'Michael Moorcock',
              'Frank Herbert',
              'Roger Zelazny',
              'Edward E. Smith',
              'Robert E. Howard',
              'Howard Phillips Lovecraft',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Prince Corwin is the Shadow Traveling protagonist of which author?': [
              'Roger Zelazny',
              'Michael Moorcock',
              'Frank Herbert',
              'Edward E. Smith',
              'Robert E. Howard',
              'Howard Phillips Lovecraft',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The Miracle drug of Spice drives much of the politics in which authors works? ': [
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Edward E. Smith',
              'Robert E. Howard',
              'Howard Phillips Lovecraft',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The Galactic Patrol defended worlds against space pirates and worse in which authors works?': [
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Robert E. Howard',
              'Howard Phillips Lovecraft',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Conan the famed hyborian barbarian fought for survival and glory in which authors works?': [
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Howard Phillips Lovecraft',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The Crawling Chaos, soul of the Outer Gods, was born from the pages of which author?': [
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'William Gibson',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Henry Dorsett Case was a “Console Cowboy” in which authors works?': [
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Isaac Asimov',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Which author introduced the idea of the Three Laws of Robotics?': [
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Robert A. Heinlein',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The verb Grok, defined in the merriam-webster dictionary as “To understand profoundly and intuitively,” was invented by which author?': [
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Poul Anderson',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The temporal policemen of The Time Patrol come from which author’s works?': [
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Walter Jon Williams',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The science fiction Comedy of Manners omnibus, “Ten Points for Style,” was written by which author?': [
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Roberta Ann MacAvoy',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'The musician and witch Damiano is the protagonist in which author’s works?': [
              'Roberta Ann MacAvoy',
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Larry Niven',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Teela Brown was bred to be lucky in which author’s works?': [
              'Larry Niven',
              'Roberta Ann MacAvoy',
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'C. J. Cherryh',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'Morgaine travel’s from world to world but ancient gates, destroying the very gates she uses in which author’s works?': [
              'C. J. Cherryh',
              'Larry Niven',
              'Roberta Ann MacAvoy',
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Ursula K. Le Guin',
              'Philip K. Dick',
            ],
        },
        {
            'You cannot lie in the language of Dragons, because it is the language of True Names, in which author’s works.': [
              'Ursula K. Le Guin',
              'C. J. Cherryh',
              'Larry Niven',
              'Roberta Ann MacAvoy',
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
              'Philip K. Dick',
            ],
        },
        {
            'Substance D, a psychoactive drug with horrible side-effects, is poisoning America in which author’s works?': [
              'Philip K. Dick',
              'Ursula K. Le Guin',
              'C. J. Cherryh',
              'Larry Niven',
              'Roberta Ann MacAvoy',
              'Walter Jon Williams',
              'Poul Anderson',
              'Robert A. Heinlein',
              'Isaac Asimov',
              'William Gibson',
              'Howard Phillips Lovecraft',
              'Robert E. Howard',
              'Edward E. Smith',
              'Frank Herbert',
              'Roger Zelazny',
              'Michael Moorcock',
            ],
        },
        {
            'Dorian Hawkmoon is?': [
              'An Incarnation of the Eternal Champion',
              'A Prince of Amber',
              'A Dragon hiding among men.',
              'A Space Policeman',
              'A Time Policeman',
              'An undercover policeman',
              'An Allowed Burglar',
              'A cyberspace hacker',
            ],
        },
        {
            'Benedict is?': [
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'A Dragon hiding among men.',
              'A Space Policeman',
              'A Time Policeman',
              'An undercover policeman',
              'An Allowed Burglar',
              'A cyberspace hacker',
            ],
        },
        {
            'Mayland Long is?': [
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'A Space Policeman',
              'A Time Policeman',
              'An undercover policeman',
              'An Allowed Burglar',
              'A cyberspace hacker',
            ],
        },
        {
            'Drake Maijstral is?': [
              'An Allowed Burglar',
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'A Space Policeman',
              'A Time Policeman',
              'An undercover policeman',
              'A cyberspace hacker',
            ],
        },
        {
            'Manse Everard is?': [
              'A Time Policeman',
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'A Space Policeman',
              'An undercover policeman',
              'An Allowed Burglar',
              'A cyberspace hacker',
            ],
        },
        {
            'Kimball Kinnison is?': [
              'A Space Policeman',
              'A Time Policeman',
              'An Allowed Burglar',
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'An undercover policeman',
              'A cyberspace hacker',
            ],
        },
        {
            'Bob Arctor is?': [
              'An undercover policeman',
              'A Space Policeman',
              'A Time Policeman',
              'An Allowed Burglar',
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
              'A cyberspace hacker',
            ],
        },
        {
            'Henry Dorsett Case?': [
              'A cyberspace hacker',
              'An undercover policeman',
              'A Space Policeman',
              'A Time Policeman',
              'An Allowed Burglar',
              'A Dragon hiding among men.',
              'A Prince of Amber',
              'An Incarnation of the Eternal Champion',
            ],
        },
        {
            'The following prayer is uttered in a work of Roger Zelazny. “Insofar as I may be heard by anything, which may or may not care what I say, I ask, if it matters, that you be forgiven for anything you may have done or failed to do which requires forgiveness. Conversely, if not forgiveness but something else may be required to insure any possible benefit for which you may be eligible after the destruction of your body, I ask that this, whatever it may be, be granted or withheld, as the case may be, in such a manner as to insure your receiving said benefit. I ask this in my capacity as your elected intermediary between yourself and that which may not be yourself, but which may have an interest in the matter of your receiving as much as it is possible for you to receive of this thing, and which may in some way be influenced by this ceremony. Amen.” Which work is it?': [
                'Creatures of Light and Darkness',
                'Lord of Light',
                'A Night in the Lonesome October',
                'The Doors of His Face, The Lamps of His Mouth, and Other Stories',
                'Lord Demon',
                'The Chronicles of Amber',
                'The Mask of Loki',
                'Jack of Shadows',
                'Dilvish, the Damned',
            ],
        },
        {
            'Which two authors shared characters?': [
                'Robert E. Howard and Howard Phillips Lovecraft',
                'Michael Moorcock and Frank Herbert',
                'Roger Zelazny and Isaac Asimov',
                'Edward E. Smith and Poul Anderson',
                'William Gibson and Robert A. Heinlein',
                'Walter Jon Williams and Roberta Ann MacAvoy',
                'Ursula K. Le Guin and Philip K. Dick',
            ],
        },
        {
            'Which title is not a compilation of previously published works?': [
                'The Word of Unbinding',
                'Stormbringer',
                'Dilvish, the Damned',
                'Ten Points for Style',
                'The Chronicles of Amber',
            ],
        },
        {
            'What is the meaning of life?': [
                'Forty two',
                'To find happiness',
                'You have to find it for yourself',
                'To pass on your genes',
                'To find meaning',
            ],
        },
        {
            'Who is Corwin\’s son?': [
                'Merlin',
                'Brand',
                'Oberon',
                'Random',
                'Eric',
            ],
        },
        {
            'Who here has not flirted with being a villain?': [
                'None of these',
                'Jack of Shadows from Jack of Shadows',
                'DuQuesne from Skylark',
                'Corwin from Chronicles of Amber',
                'Elric of Melniboné of Elric of Melniboné',
            ],
        },
    ],
};
